### ISSUE TITLE
scTHI.score error: undefined columns selected

### ISSUE THREAD

**Issue by pbrazda** [miccec/scTHI#2]
Hi, 

I'm trying to reproduce the **MGH45 analysis**, as described in the wiki.
However, at 

`MGH45.result <- scTHI.score(expMat = MGH45, cellCusterA = Malignant, cellCusterB = Myeloid,  cellCusterAName = "Tumor", cellCusterBName = "Myeloid",   topRank = 10, PValue = TRUE, pvalueCutoff = 0.05, nPermu = 100, ncore = 4)`

I run into

```
Warning: Not all interaction genes are in expMat
Computing score for 2323 interaction pairs...
Error in `[.data.frame`(ddataA, ggenes1, cellCusterA, drop = F) : 
  undefined columns selected
```

Tips?

Thank you!

Best, 
Peter

**Comment by miccec** [comment]
Hi, 
thanks for your comments. The error was generated for a wrong format of the annotation. If you loead the annotation as:
```
MGH45.annotation <- read.csv(url("https://github.com/miccec/scTHI.datasets/raw/master/MGH45annotation.csv"),as.is=TRUE)
```
everything will work file
