### ISSUE TITLE
Cannot find object interaction_table

### ISSUE THREAD

**Issue by jonathan-f** [miccec/scTHI#3]
Hello,
I read on the documentation that the ligand-receptor database is available as an object in the R package. I installed both scTHI and scTHI.data but I couldn't find the object interaction_table; have I misunderstood something?

Thank you, 
Best wishes,
Jonathan

**Comment by miccec** [comment]
Hi @jonathan-f ,
thanks for your interest in scTHI, the interaction_table object is part of  internal data of the package and is available for download here: https://github.com/miccec/scTHI/blob/master/R/sysdata.rda
